## Basic Commands

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype = 'int16') #Create 1D array
print(a)

[1 2 3]


In [3]:
b = np.array([[3.7,7.9,4.4,2.6],[3.9,6.3,7.0,9.9]]) #Create 2D array
print(b)

[[3.7 7.9 4.4 2.6]
 [3.9 6.3 7.  9.9]]


In [4]:
print(a.ndim) #Dimensions of a

1


In [5]:
print(b.ndim) #Dimensions of b

2


In [6]:
print(a.shape) #Get Shape of a (colums)

(3,)


In [7]:
print(b.shape) #Get the Shape of b (rows and columns)

(2, 4)


In [8]:
print(a.dtype) #Get type

int16


In [9]:
print(a.itemsize) #Number of bytes taken up

2


In [10]:
print(a.nbytes) #Total bytes

6


## Array handling

### 2D Array

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
print(a[1,-2]) #Access specific element

13


In [13]:
print(a[0,:]) #Access specific row

[1 2 3 4 5 6 7]


In [14]:
print(a[:,1]) #Access specific column

[2 9]


In [15]:
print(a[0,1:6:2]) #[row, start index : end index : step]

[2 4 6]


In [16]:
a[:,2] = [1,2] #Change elements of a column
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


### 3D array

In [17]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
print(b[0][1][:]) #Get specific element

[3 4]


## Initializing Arrays

In [19]:
print(np.zeros((2,3))) #Array of zeros

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((4,2), dtype = 'int32')) #Array of ones

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [21]:
print(np.full((2,2), 100)) #Array of given number

[[100 100]
 [100 100]]


In [22]:
#Array with the same shape as another
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(np.full(a.shape, 6),"\n")
print(np.full_like(a,6))

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]] 

[[6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6]]


In [23]:
print(np.random.rand(4,2)) #Array or random decimals

[[0.09616867 0.02155264]
 [0.06007436 0.62026001]
 [0.57043797 0.46187837]
 [0.22612517 0.93747618]]


In [24]:
print(np.random.random_sample(a.shape)) #Array of random decimals in the shape of another array

[[0.31128604 0.923652   0.60247026 0.1688913  0.8764763  0.04979553
  0.34422954]
 [0.45799713 0.76068958 0.27724309 0.82429805 0.97252358 0.0236406
  0.37744353]]


In [25]:
print(np.random.randint(4,7,size = (3,3))) #Array of random integers, exclusive

[[4 5 4]
 [6 4 4]
 [6 5 5]]


In [26]:
print(np.identity(5)) #Identity matrix of given dimension

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
arr = np.array([[1,2,3]]) #Create copies of the array
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
arr = np.zeros((5,5), dtype = 'int8') #Make ones
arr[0:5:4][:] +=1
arr[1:4,0:6:4] +=1
arr[2,2] += 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [29]:
arr = np.ones((5,5), dtype='int8')
arr[1:4,1:4] = np.zeros((3,3))
arr[2][2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [30]:
#When creating a copy of an array, use .copy()
a = np.array([1,2,3])
b = a
b[0] = 100
print("Before :")
print(b)
print(a)

print("\n")
a = np.array([1,2,3])
b = a.copy()
b[0] = 10
print("After: ")
print(b)
print(a)

Before :
[100   2   3]
[100   2   3]


After: 
[10  2  3]
[1 2 3]


## Mathematics

In [34]:
a = np.array([1,2,3,4]) #Basic arithmetic
print(a*2)
print(a/2)
print(a+2)
print(a-2)

[2 4 6 8]
[0.5 1.  1.5 2. ]
[3 4 5 6]
[-1  0  1  2]


In [38]:
print(np.sin(a)) #Trigonometry
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


### Linear algebra

In [42]:
#Matrix Multiplication
a = np.ones((2,3))
b = np.full((3,2), 2)
print(np.matmul(a,b))

[[6. 6.]
 [6. 6.]]


In [43]:
#Determinant
c = np.identity(3)
print(np.linalg.det(c))

1.0


### Statistics

In [57]:
stats = np.array([[1,12,23], [42,15,60],[73,88,9]])

print(np.max(stats)) #Maximum of the entire array
print(np.max(stats, axis=1)) #Maximum of each row
print(np.max(stats, axis = 0)) #Maximum of each column

88
[23 60 88]
[73 88 60]


In [60]:
print(np.sum(stats)) #Sum of the entire array
print(np.sum(stats, axis = 1)) #Sum of each row
print(np.sum(stats, axis = 0)) #Sum of each column

323
[ 36 117 170]
[116 115  92]


## Reorganizing Arrays

In [67]:
#Reshaping arrays
before = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
after = before.reshape((2,6))
print(after)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [71]:
#Vertically stacking arrays
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
#Vertically stacking arrays
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

print(np.hstack([h1,h2]))

[1 2 3 4 5 6 7 8]


## Misc

### Advanced Indexing and Boolean Masking

In [78]:
filedata = np.genfromtxt("data.txt", delimiter = ",") #Load in data
filedata = filedata.astype("int32") #Convert to int
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [81]:
print(filedata > 50) # if the value > 50

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


In [82]:
print(filedata[filedata > 50]) #Outputting values > 50

[196  75 766  75  55 999  78  76  88]


In [88]:
a = np.array([1,2,3,4,5,6,8,9,10])

print(a[[1,8]]) #Converts from counting to index

[ 2 10]


In [95]:
print(np.any(filedata > 50, axis = 1),"\n") #Check if each row has a value > 50
print(np.any(filedata > 50, axis = 0)) #Check if each column has a value > 50

[ True  True  True] 

[False False False False  True  True False  True  True False False False
 False False False False  True  True]


In [96]:
print(np.all(filedata > 50, axis = 1),"\n") #Check if the entire row has a value > 50
print(np.all(filedata > 50, axis = 0)) #Check if the entire column has a value > 50

[False False False] 

[False False False False  True False False False False False False False
 False False False False False False]


In [98]:
print( (filedata > 50) & (filedata < 100)) #Find where values > 50 and values < 100

[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]


In [113]:
a = np.linspace(1,30,30, dtype="int8")
a = a.reshape((6,5))

print(a,"\n")
print(a[2:4, 0:2],"\n")

print(a[[0,1,2,3], [1,2,3,4]],"\n")

print(a[[0,4,5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[11 12]
 [16 17]] 

[ 2  8 14 20] 

[[ 4  5]
 [24 25]
 [29 30]]
